version: '3.1'

services:
  springboot:
    image: dockerhandson/uzy-notice:latest
#    restart: always # This will be ignored if we deploy in docker swarm
    container_name: springboot
    ports:
      - 9100:9100
    working_dir: /mnt/workspace/server/common/
    depends_on:
      - mongo
#    deploy:  # This will be considered only in docker swarm.
#      replicas: 2
#      update_config:
#        parallelism: 1
#        delay: 20s
#      restart_policy:
#        condition: on-failure
#        delay: 10s
#        max_attempts: 5

  mongo:
    image: mongo
    container_name: uzy-notice
#    ports:  # for demo/debug purpose only
#      - 27018:27017
    volumes:
      - data:/root/mongo/db
    restart: always
    

