server:
  port: 9100
  servlet:
    context-path: /notice
nature:
  restApi:
    enabled: true

spring:
  freemarker:
    check-template-location: false
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  application:
    name: notice
    version: 1.0.0
    description: springboot notice server

  data:
    mongodb:
      database: notice
      uri: mongodb://127.0.0.1:27017
      authentication-database: admin

  resources:
    static-locations: classpath:/static/,classpath:/templates/

  mvc:
    static-path-pattern: /**
